# The following is automatically generated by numba_layers_generator.py

from numpy import bool_
from numpy import float64
from numpy import int64
from numpy import uint64
from numpy import uintp

###

from mcdc.code_factory.numba_layers_generator import into_dtype

particle_data = into_dtype([
    ('x', float64),
    ('y', float64),
    ('z', float64),
    ('t', float64),
    ('ux', float64),
    ('uy', float64),
    ('uz', float64),
    ('g', int64),
    ('E', float64),
    ('w', float64),
    ('particle_type', int64),
    ('rng_seed', uint64),
])

particle = into_dtype([
    ('cell_ID', int64),
    ('material_ID', int64),
    ('surface_ID', int64),
    ('alive', bool),
    ('fresh', bool),
    ('event', int64),
    ('x', float64),
    ('y', float64),
    ('z', float64),
    ('t', float64),
    ('ux', float64),
    ('uy', float64),
    ('uz', float64),
    ('g', int64),
    ('E', float64),
    ('w', float64),
    ('particle_type', int64),
    ('rng_seed', uint64),
])

cell = into_dtype([
    ('name', 'U32'),
    ('region_RPN_tokens_offset', int64),
    ('region_RPN_tokens_length', int64),
    ('N_surface', int64),
    ('surface_IDs_offset', int64),
    ('fill_type', int64),
    ('fill_ID', int64),
    ('fill_translated', bool),
    ('fill_rotated', bool),
    ('translation', float64, (3,)),
    ('rotation', float64, (3,)),
    ('N_collision_tally', int64),
    ('collision_tally_IDs_offset', int64),
    ('N_tracklength_tally', int64),
    ('tracklength_tally_IDs_offset', int64),
    ('ID', int64),
])

lattice = into_dtype([
    ('name', 'U32'),
    ('x0', float64),
    ('dx', float64),
    ('Nx', int64),
    ('y0', float64),
    ('dy', float64),
    ('Ny', int64),
    ('z0', float64),
    ('dz', float64),
    ('Nz', int64),
    ('universe_IDs_offset', int64),
    ('universe_IDs_length', int64),
    ('ID', int64),
])

material = into_dtype([
    ('name', 'U32'),
    ('temperature', float64),
    ('fissionable', bool),
    ('has_neutron_multigroup', bool),
    ('neutron_multigroup_ID', int64),
    ('N_nuclide', int64),
    ('nuclide_IDs_offset', int64),
    ('N_element', int64),
    ('element_IDs_offset', int64),
    ('nuclide_densities_offset', int64),
    ('nuclide_densities_length', int64),
    ('element_densities_offset', int64),
    ('element_densities_length', int64),
    ('ID', int64),
])

collision_tally = into_dtype([
    ('cell_filtered', bool),
    ('cell_filter_ID', int64),
    ('mesh_filtered', bool),
    ('mesh_filter_type', int64),
    ('mesh_filter_ID', int64),
    ('mesh_stride_z', int64),
    ('mesh_stride_y', int64),
    ('mesh_stride_x', int64),
    ('ID', int64),
    ('base_ID', int64),
])

tracklength_tally = into_dtype([
    ('cell_filtered', bool),
    ('cell_filter_ID', int64),
    ('mesh_filtered', bool),
    ('mesh_filter_type', int64),
    ('mesh_filter_ID', int64),
    ('mesh_stride_z', int64),
    ('mesh_stride_y', int64),
    ('mesh_stride_x', int64),
    ('ID', int64),
    ('base_ID', int64),
])

universe = into_dtype([
    ('name', 'U32'),
    ('N_cell', int64),
    ('cell_IDs_offset', int64),
    ('ID', int64),
])

data = into_dtype([
    ('ID', int64),
    ('sub_type', int64),
    ('sub_ID', int64),
])

none_data = into_dtype([
    ('ID', int64),
    ('base_ID', int64),
])

polynomial_data = into_dtype([
    ('coefficients_offset', int64),
    ('coefficients_length', int64),
    ('ID', int64),
    ('base_ID', int64),
])

table_data = into_dtype([
    ('N', int64),
    ('x_offset', int64),
    ('x_length', int64),
    ('y_offset', int64),
    ('y_length', int64),
    ('interpolations_offset', int64),
    ('interpolations_length', int64),
    ('interpolation_boundaries_offset', int64),
    ('interpolation_boundaries_length', int64),
    ('N_aux', int64),
    ('aux_offset', int64),
    ('aux_length', int64),
    ('ID', int64),
    ('base_ID', int64),
])

distribution = into_dtype([
    ('ID', int64),
    ('sub_type', int64),
    ('sub_ID', int64),
])

evaporation_distribution = into_dtype([
    ('nuclear_temperature_ID', int64),
    ('restriction_energy', float64),
    ('ID', int64),
    ('base_ID', int64),
])

kalbach_mann_distribution = into_dtype([
    ('energy_offset', int64),
    ('energy_length', int64),
    ('offset_offset', int64),
    ('offset_length', int64),
    ('energy_out_offset', int64),
    ('energy_out_length', int64),
    ('pdf_offset', int64),
    ('pdf_length', int64),
    ('cdf_offset', int64),
    ('cdf_length', int64),
    ('precompound_factor_offset', int64),
    ('precompound_factor_length', int64),
    ('angular_slope_offset', int64),
    ('angular_slope_length', int64),
    ('ID', int64),
    ('base_ID', int64),
])

level_scattering_distribution = into_dtype([
    ('C1', float64),
    ('C2', float64),
    ('ID', int64),
    ('base_ID', int64),
])

maxwellian_distribution = into_dtype([
    ('nuclear_temperature_ID', int64),
    ('restriction_energy', float64),
    ('ID', int64),
    ('base_ID', int64),
])

multi_table_distribution = into_dtype([
    ('grid_offset', int64),
    ('grid_length', int64),
    ('N_table', int64),
    ('table_IDs_offset', int64),
    ('ID', int64),
    ('base_ID', int64),
])

nbody_distribution = into_dtype([
    ('pdf_ID', int64),
    ('ID', int64),
    ('base_ID', int64),
])

none_distribution = into_dtype([
    ('ID', int64),
    ('base_ID', int64),
])

pmf_distribution = into_dtype([
    ('value_offset', int64),
    ('value_length', int64),
    ('pmf_offset', int64),
    ('pmf_length', int64),
    ('cmf_offset', int64),
    ('cmf_length', int64),
    ('ID', int64),
    ('base_ID', int64),
])

tabulated_distribution = into_dtype([
    ('pdf_ID', int64),
    ('ID', int64),
    ('base_ID', int64),
])

tabulated_energy_angle_distribution = into_dtype([
    ('energy_offset', int64),
    ('energy_length', int64),
    ('offset_offset', int64),
    ('offset_length', int64),
    ('energy_out_offset', int64),
    ('energy_out_length', int64),
    ('pdf_offset', int64),
    ('pdf_length', int64),
    ('cdf_offset', int64),
    ('cdf_length', int64),
    ('cosine_offset__offset', int64),
    ('cosine_offset__length', int64),
    ('cosine_offset', int64),
    ('cosine_length', int64),
    ('cosine_pdf_offset', int64),
    ('cosine_pdf_length', int64),
    ('cosine_cdf_offset', int64),
    ('cosine_cdf_length', int64),
    ('ID', int64),
    ('base_ID', int64),
])

electron_reaction = into_dtype([
    ('MT', int64),
    ('xs_offset', int64),
    ('xs_length', int64),
    ('xs_offset_', int64),
    ('reference_frame', int64),
    ('ID', int64),
    ('sub_type', int64),
    ('sub_ID', int64),
])

electron_bremsstrahlung_reaction = into_dtype([
    ('eloss_ID', int64),
    ('ID', int64),
    ('base_ID', int64),
])

electron_elastic_scattering_reaction = into_dtype([
    ('mu_cut', float64),
    ('xs_large_ID', int64),
    ('mu_ID', int64),
    ('ID', int64),
    ('base_ID', int64),
])

electron_excitation_reaction = into_dtype([
    ('eloss_ID', int64),
    ('ID', int64),
    ('base_ID', int64),
])

electron_ionization_reaction = into_dtype([
    ('N_subshell', int64),
    ('N_subshell_x', int64),
    ('subshell_x_IDs_offset', int64),
    ('N_subshell_product', int64),
    ('subshell_product_IDs_offset', int64),
    ('ID', int64),
    ('base_ID', int64),
])

element = into_dtype([
    ('name', 'U32'),
    ('atomic_weight_ratio', float64),
    ('atomic_number', int64),
    ('electron_xs_energy_grid_offset', int64),
    ('electron_xs_energy_grid_length', int64),
    ('electron_total_xs_offset', int64),
    ('electron_total_xs_length', int64),
    ('electron_ionization_xs_offset', int64),
    ('electron_ionization_xs_length', int64),
    ('electron_elastic_xs_offset', int64),
    ('electron_elastic_xs_length', int64),
    ('electron_excitation_xs_offset', int64),
    ('electron_excitation_xs_length', int64),
    ('electron_bremsstrahlung_xs_offset', int64),
    ('electron_bremsstrahlung_xs_length', int64),
    ('N_electron_ionization_reaction', int64),
    ('electron_ionization_reaction_IDs_offset', int64),
    ('N_electron_elastic_scattering_reaction', int64),
    ('electron_elastic_scattering_reaction_IDs_offset', int64),
    ('N_electron_excitation_reaction', int64),
    ('electron_excitation_reaction_IDs_offset', int64),
    ('N_electron_bremsstrahlung_reaction', int64),
    ('electron_bremsstrahlung_reaction_IDs_offset', int64),
    ('electron_ionization_subshell_binding_energy_offset', int64),
    ('electron_ionization_subshell_binding_energy_length', int64),
    ('ID', int64),
])

neutron_multigroup_data = into_dtype([
    ('G', int64),
    ('J', int64),
    ('energy_grid_offset', int64),
    ('energy_grid_length', int64),
    ('energy_representation', int64),
    ('speed_offset', int64),
    ('speed_length', int64),
    ('decay_rate_offset', int64),
    ('decay_rate_length', int64),
    ('capture_offset', int64),
    ('capture_length', int64),
    ('scatter_offset', int64),
    ('scatter_length', int64),
    ('fission_offset', int64),
    ('fission_length', int64),
    ('total_offset', int64),
    ('total_length', int64),
    ('nu_s_offset', int64),
    ('nu_s_length', int64),
    ('nu_p_offset', int64),
    ('nu_p_length', int64),
    ('nu_d_offset', int64),
    ('nu_d_length', int64),
    ('nu_d_total_offset', int64),
    ('nu_d_total_length', int64),
    ('nu_f_offset', int64),
    ('nu_f_length', int64),
    ('chi_s_offset', int64),
    ('chi_s_length', int64),
    ('chi_p_offset', int64),
    ('chi_p_length', int64),
    ('chi_d_offset', int64),
    ('chi_d_length', int64),
    ('fissionable', bool),
    ('ID', int64),
])

nuclide = into_dtype([
    ('name', 'U32'),
    ('temperature', float64),
    ('atomic_number', int64),
    ('mass_number', int64),
    ('atomic_weight_ratio', float64),
    ('fissionable', bool),
    ('excitation_level', int64),
    ('neutron_xs_energy_grid_offset', int64),
    ('neutron_xs_energy_grid_length', int64),
    ('neutron_total_xs_offset', int64),
    ('neutron_total_xs_length', int64),
    ('neutron_elastic_xs_offset', int64),
    ('neutron_elastic_xs_length', int64),
    ('neutron_capture_xs_offset', int64),
    ('neutron_capture_xs_length', int64),
    ('neutron_inelastic_xs_offset', int64),
    ('neutron_inelastic_xs_length', int64),
    ('neutron_fission_xs_offset', int64),
    ('neutron_fission_xs_length', int64),
    ('N_neutron_elastic_scattering_reaction', int64),
    ('neutron_elastic_scattering_reaction_IDs_offset', int64),
    ('N_neutron_capture_reaction', int64),
    ('neutron_capture_reaction_IDs_offset', int64),
    ('N_neutron_inelastic_scattering_reaction', int64),
    ('neutron_inelastic_scattering_reaction_IDs_offset', int64),
    ('N_neutron_fission_reaction', int64),
    ('neutron_fission_reaction_IDs_offset', int64),
    ('neutron_fission_prompt_multiplicity_ID', int64),
    ('neutron_fission_delayed_multiplicity_ID', int64),
    ('N_neutron_fission_delayed_precursor', int64),
    ('neutron_fission_delayed_fractions_offset', int64),
    ('neutron_fission_delayed_fractions_length', int64),
    ('neutron_fission_delayed_decay_rates_offset', int64),
    ('neutron_fission_delayed_decay_rates_length', int64),
    ('N_neutron_fission_delayed_spectrum', int64),
    ('neutron_fission_delayed_spectrum_IDs_offset', int64),
    ('ID', int64),
])

mesh = into_dtype([
    ('name', 'U32'),
    ('N_bin', int64),
    ('Nx', int64),
    ('Ny', int64),
    ('Nz', int64),
    ('ID', int64),
    ('sub_type', int64),
    ('sub_ID', int64),
])

structured_mesh = into_dtype([
    ('x_offset', int64),
    ('x_length', int64),
    ('y_offset', int64),
    ('y_length', int64),
    ('z_offset', int64),
    ('z_length', int64),
    ('ID', int64),
    ('base_ID', int64),
])

uniform_mesh = into_dtype([
    ('x0', float64),
    ('dx', float64),
    ('Nx', int64),
    ('y0', float64),
    ('dy', float64),
    ('Ny', int64),
    ('z0', float64),
    ('dz', float64),
    ('Nz', int64),
    ('ID', int64),
    ('base_ID', int64),
])

neutron_reaction = into_dtype([
    ('MT', int64),
    ('xs_offset', int64),
    ('xs_length', int64),
    ('xs_offset_', int64),
    ('reference_frame', int64),
    ('q_value', float64),
    ('ID', int64),
    ('sub_type', int64),
    ('sub_ID', int64),
])

neutron_capture_reaction = into_dtype([
    ('ID', int64),
    ('base_ID', int64),
])

neutron_elastic_scattering_reaction = into_dtype([
    ('mu_table_ID', int64),
    ('ID', int64),
    ('base_ID', int64),
])

neutron_fission_reaction = into_dtype([
    ('angle_type', int64),
    ('mu_ID', int64),
    ('spectrum_ID', int64),
    ('ID', int64),
    ('base_ID', int64),
])

neutron_inelastic_scattering_reaction = into_dtype([
    ('multiplicity', int64),
    ('angle_type', int64),
    ('mu_ID', int64),
    ('N_spectrum_probability_bin', int64),
    ('N_spectrum', int64),
    ('spectrum_probability_grid_offset', int64),
    ('spectrum_probability_grid_length', int64),
    ('spectrum_probability_offset', int64),
    ('spectrum_probability_length', int64),
    ('N_energy_spectrum', int64),
    ('energy_spectrum_IDs_offset', int64),
    ('ID', int64),
    ('base_ID', int64),
])

collision_data = into_dtype([
    ('energy_deposition', float64),
])

particle_bank = into_dtype([
    ('size', int64, (1,)),
    ('tag', 'U32'),
])

settings = into_dtype([
    ('N_particle', int64),
    ('N_batch', int64),
    ('rng_seed', int64),
    ('N_inactive', int64),
    ('N_active', int64),
    ('N_cycle', int64),
    ('k_init', float64),
    ('use_gyration_radius', bool),
    ('gyration_radius_type', int64),
    ('use_source_file', bool),
    ('source_file_name', 'U32'),
    ('time_boundary', float64),
    ('output_name', 'U32'),
    ('use_progress_bar', bool),
    ('N_census', int64),
    ('census_time_offset', int64),
    ('census_time_length', int64),
    ('use_census_based_tally', bool),
    ('census_tally_frequency', int64),
    ('save_particle', bool),
    ('active_bank_buffer', int64),
    ('census_bank_buffer_ratio', float64),
    ('source_bank_buffer_ratio', float64),
    ('future_bank_buffer_ratio', float64),
    ('neutron_transport', bool),
    ('electron_transport', bool),
    ('proton_transport', bool),
    ('neutron_eigenvalue_mode', bool),
    ('gpu_strategy', int64),
    ('gpu_async_type', int64),
    ('gpu_storage', int64),
])

neutron_multigroup = into_dtype([
    ('multigrid', bool),
])

implicit_capture = into_dtype([
    ('active', bool),
])

weighted_emission = into_dtype([
    ('active', bool),
    ('weight_target', float64),
])

global_weight_roulette = into_dtype([
    ('active', bool),
    ('weight_threshold', float64),
    ('weight_target', float64),
])

weight_windows = into_dtype([
    ('active', bool),
    ('energy_bounds_offset', int64),
    ('energy_bounds_length', int64),
    ('Ne', int64),
    ('mesh_ID', int64),
    ('Nx', int64),
    ('Ny', int64),
    ('Nz', int64),
    ('lower_weights_offset', int64),
    ('lower_weights_length', int64),
    ('target_weights_offset', int64),
    ('target_weights_length', int64),
    ('upper_weights_offset', int64),
    ('upper_weights_length', int64),
])

population_control = into_dtype([
    ('active', bool),
])

technique = into_dtype([
    ('neutron_multigroup', neutron_multigroup),
    ('implicit_capture', implicit_capture),
    ('weighted_emission', weighted_emission),
    ('global_weight_roulette', global_weight_roulette),
    ('weight_windows', weight_windows),
    ('population_control', population_control),
])

source = into_dtype([
    ('name', 'U32'),
    ('point_source', bool),
    ('point', float64, (3,)),
    ('x', float64, (2,)),
    ('y', float64, (2,)),
    ('z', float64, (2,)),
    ('isotropic_direction', bool),
    ('mono_direction', bool),
    ('white_direction', bool),
    ('direction', float64, (3,)),
    ('polar_cosine', float64, (2,)),
    ('azimuthal', float64, (2,)),
    ('mono_energetic', bool),
    ('energy_group', int64),
    ('energy', float64),
    ('energy_group_pmf_ID', int64),
    ('energy_pdf_ID', int64),
    ('discrete_time', bool),
    ('time', float64),
    ('time_range', float64, (2,)),
    ('particle_type', int64),
    ('probability', float64),
    ('moving', bool),
    ('N_move', int64),
    ('N_move_grid', int64),
    ('move_velocities_offset', int64),
    ('move_velocities_length', int64),
    ('move_durations_offset', int64),
    ('move_durations_length', int64),
    ('move_time_grid_offset', int64),
    ('move_time_grid_length', int64),
    ('move_translations_offset', int64),
    ('move_translations_length', int64),
    ('ID', int64),
])

surface = into_dtype([
    ('type', int64),
    ('name', 'U32'),
    ('boundary_condition', int64),
    ('A', float64),
    ('B', float64),
    ('C', float64),
    ('D', float64),
    ('E', float64),
    ('F', float64),
    ('G', float64),
    ('H', float64),
    ('I', float64),
    ('J', float64),
    ('R', float64),
    ('r', float64),
    ('linear', bool),
    ('quadric', bool),
    ('quartic', bool),
    ('nx', float64),
    ('ny', float64),
    ('nz', float64),
    ('moving', bool),
    ('N_move', int64),
    ('N_move_grid', int64),
    ('move_velocities_offset', int64),
    ('move_velocities_length', int64),
    ('move_durations_offset', int64),
    ('move_durations_length', int64),
    ('move_time_grid_offset', int64),
    ('move_time_grid_length', int64),
    ('move_translations_offset', int64),
    ('move_translations_length', int64),
    ('N_surface_crossing_tally', int64),
    ('surface_crossing_tally_IDs_offset', int64),
    ('ID', int64),
])

surface_crossing_tally = into_dtype([
    ('surface_filtered', bool),
    ('surface_filter_ID', int64),
    ('cell_filtered', bool),
    ('cell_filter_ID', int64),
    ('ID', int64),
    ('base_ID', int64),
])

tally = into_dtype([
    ('name', 'U32'),
    ('scores_offset', int64),
    ('scores_length', int64),
    ('filter_direction', bool),
    ('filter_energy', bool),
    ('filter_time', bool),
    ('mu_offset', int64),
    ('mu_length', int64),
    ('azi_offset', int64),
    ('azi_length', int64),
    ('polar_reference', float64, (3,)),
    ('energy_offset', int64),
    ('energy_length', int64),
    ('time_offset', int64),
    ('time_length', int64),
    ('bin_offset', int64),
    ('bin_length', int64),
    ('bin_sum_offset', int64),
    ('bin_sum_length', int64),
    ('bin_sum_square_offset', int64),
    ('bin_sum_square_length', int64),
    ('bin_shape_offset', int64),
    ('bin_shape_length', int64),
    ('stride_mu', int64),
    ('stride_azi', int64),
    ('stride_energy', int64),
    ('stride_time', int64),
    ('ID', int64),
    ('sub_type', int64),
    ('sub_ID', int64),
])

gpu_meta = into_dtype([
    ('state_pointer', uintp),
    ('program_pointer', uintp),
    ('simulation_pointer', uintp),
    ('data_pointer', uintp),
])

bank_active = None
def set_bank_active(N: dict):
    global bank_active
    bank_active = into_dtype([
        ('size', int64, (1,)),
        ('tag', 'U32'),
        ('particle_data', particle_data, (N['particle_data'],)),
    ])

bank_census = None
def set_bank_census(N: dict):
    global bank_census
    bank_census = into_dtype([
        ('size', int64, (1,)),
        ('tag', 'U32'),
        ('particle_data', particle_data, (N['particle_data'],)),
    ])

bank_source = None
def set_bank_source(N: dict):
    global bank_source
    bank_source = into_dtype([
        ('size', int64, (1,)),
        ('tag', 'U32'),
        ('particle_data', particle_data, (N['particle_data'],)),
    ])

bank_future = None
def set_bank_future(N: dict):
    global bank_future
    bank_future = into_dtype([
        ('size', int64, (1,)),
        ('tag', 'U32'),
        ('particle_data', particle_data, (N['particle_data'],)),
    ])

simulation = None
def set_simulation(N: dict):
    global simulation
    simulation = into_dtype([
        ('data', data, (N['data'])),
        ('N_data', int64),
        ('none_data', none_data, (N['none_data'])),
        ('N_none_data', int64),
        ('polynomial_data', polynomial_data, (N['polynomial_data'])),
        ('N_polynomial_data', int64),
        ('table_data', table_data, (N['table_data'])),
        ('N_table_data', int64),
        ('distributions', distribution, (N['distribution'])),
        ('N_distribution', int64),
        ('evaporation_distributions', evaporation_distribution, (N['evaporation_distribution'])),
        ('N_evaporation_distribution', int64),
        ('kalbach_mann_distributions', kalbach_mann_distribution, (N['kalbach_mann_distribution'])),
        ('N_kalbach_mann_distribution', int64),
        ('level_scattering_distributions', level_scattering_distribution, (N['level_scattering_distribution'])),
        ('N_level_scattering_distribution', int64),
        ('maxwellian_distributions', maxwellian_distribution, (N['maxwellian_distribution'])),
        ('N_maxwellian_distribution', int64),
        ('multi_table_distributions', multi_table_distribution, (N['multi_table_distribution'])),
        ('N_multi_table_distribution', int64),
        ('nbody_distributions', nbody_distribution, (N['nbody_distribution'])),
        ('N_nbody_distribution', int64),
        ('none_distributions', none_distribution, (N['none_distribution'])),
        ('N_none_distribution', int64),
        ('pmf_distributions', pmf_distribution, (N['pmf_distribution'])),
        ('N_pmf_distribution', int64),
        ('tabulated_distributions', tabulated_distribution, (N['tabulated_distribution'])),
        ('N_tabulated_distribution', int64),
        ('tabulated_energy_angle_distributions', tabulated_energy_angle_distribution, (N['tabulated_energy_angle_distribution'])),
        ('N_tabulated_energy_angle_distribution', int64),
        ('neutron_reactions', neutron_reaction, (N['neutron_reaction'])),
        ('N_neutron_reaction', int64),
        ('neutron_capture_reactions', neutron_capture_reaction, (N['neutron_capture_reaction'])),
        ('N_neutron_capture_reaction', int64),
        ('neutron_elastic_scattering_reactions', neutron_elastic_scattering_reaction, (N['neutron_elastic_scattering_reaction'])),
        ('N_neutron_elastic_scattering_reaction', int64),
        ('neutron_fission_reactions', neutron_fission_reaction, (N['neutron_fission_reaction'])),
        ('N_neutron_fission_reaction', int64),
        ('neutron_inelastic_scattering_reactions', neutron_inelastic_scattering_reaction, (N['neutron_inelastic_scattering_reaction'])),
        ('N_neutron_inelastic_scattering_reaction', int64),
        ('electron_reactions', electron_reaction, (N['electron_reaction'])),
        ('N_electron_reaction', int64),
        ('electron_bremsstrahlung_reactions', electron_bremsstrahlung_reaction, (N['electron_bremsstrahlung_reaction'])),
        ('N_electron_bremsstrahlung_reaction', int64),
        ('electron_elastic_scattering_reactions', electron_elastic_scattering_reaction, (N['electron_elastic_scattering_reaction'])),
        ('N_electron_elastic_scattering_reaction', int64),
        ('electron_excitation_reactions', electron_excitation_reaction, (N['electron_excitation_reaction'])),
        ('N_electron_excitation_reaction', int64),
        ('electron_ionization_reactions', electron_ionization_reaction, (N['electron_ionization_reaction'])),
        ('N_electron_ionization_reaction', int64),
        ('nuclides', nuclide, (N['nuclide'])),
        ('N_nuclide', int64),
        ('elements', element, (N['element'])),
        ('N_element', int64),
        ('materials', material, (N['material'])),
        ('N_material', int64),
        ('neutron_multigroup_data', neutron_multigroup_data, (N['neutron_multigroup_data'])),
        ('N_neutron_multigroup_data', int64),
        ('sources', source, (N['source'])),
        ('N_source', int64),
        ('surfaces', surface, (N['surface'])),
        ('N_surface', int64),
        ('cells', cell, (N['cell'])),
        ('N_cell', int64),
        ('universes', universe, (N['universe'])),
        ('N_universe', int64),
        ('lattices', lattice, (N['lattice'])),
        ('N_lattice', int64),
        ('meshes', mesh, (N['mesh'])),
        ('N_mesh', int64),
        ('structured_meshes', structured_mesh, (N['structured_mesh'])),
        ('N_structured_mesh', int64),
        ('uniform_meshes', uniform_mesh, (N['uniform_mesh'])),
        ('N_uniform_mesh', int64),
        ('collision_tallies', collision_tally, (N['collision_tally'])),
        ('N_collision_tally', int64),
        ('tracklength_tallies', tracklength_tally, (N['tracklength_tally'])),
        ('N_tracklength_tally', int64),
        ('surface_crossing_tallies', surface_crossing_tally, (N['surface_crossing_tally'])),
        ('N_surface_crossing_tally', int64),
        ('tallies', tally, (N['tally'])),
        ('N_tally', int64),
        ('settings', settings),
        ('technique', technique),
        ('gpu_meta', gpu_meta),
        ('bank_future', bank_future),
        ('bank_source', bank_source),
        ('bank_census', bank_census),
        ('bank_active', bank_active),
        ('name', 'U32'),
        ('idx_work', int64),
        ('idx_cycle', int64),
        ('idx_census', int64),
        ('idx_batch', int64),
        ('k_eff', float64),
        ('k_cycle_offset', int64),
        ('k_cycle_length', int64),
        ('k_avg', float64),
        ('k_sdv', float64),
        ('k_avg_running', float64),
        ('k_sdv_running', float64),
        ('n_avg', float64),
        ('n_sdv', float64),
        ('n_max', float64),
        ('C_avg', float64),
        ('C_sdv', float64),
        ('C_max', float64),
        ('eigenvalue_tally_nuSigmaF', float64, (1,)),
        ('eigenvalue_tally_n', float64, (1,)),
        ('eigenvalue_tally_C', float64, (1,)),
        ('gyration_radius_offset', int64),
        ('gyration_radius_length', int64),
        ('cycle_active', bool),
        ('mpi_size', int64),
        ('mpi_rank', int64),
        ('mpi_master', bool),
        ('mpi_work_start', int64),
        ('mpi_work_size', int64),
        ('mpi_work_size_total', int64),
        ('mpi_work_iter', int64, (1,)),
        ('runtime_total', float64),
        ('runtime_preparation', float64),
        ('runtime_simulation', float64),
        ('runtime_output', float64),
        ('runtime_bank_management', float64),
        ('source_seed', int64),
    ])

