# The following is automatically generated by code_factory.py

from numba import njit


@njit
def energy_grid(index, mgxs, data):
    offset = mgxs["energy_grid_offset"]
    return data[offset + index]


@njit
def energy_grid_all(mgxs, data):
    start = mgxs["energy_grid_offset"]
    size = mgxs["G"] + 1
    end = start + size
    return data[start:end]


@njit
def energy_grid_last(mgxs, data):
    start = mgxs["energy_grid_offset"]
    size = mgxs["G"] + 1
    end = start + size
    return data[end - 1]


@njit
def energy_grid_chunk(start, length, mgxs, data):
    start += mgxs["energy_grid_offset"]
    end = start + length
    return data[start:end]


@njit
def speed(index, mgxs, data):
    offset = mgxs["speed_offset"]
    return data[offset + index]


@njit
def speed_all(mgxs, data):
    start = mgxs["speed_offset"]
    size = mgxs["G"]
    end = start + size
    return data[start:end]


@njit
def speed_last(mgxs, data):
    start = mgxs["speed_offset"]
    size = mgxs["G"]
    end = start + size
    return data[end - 1]


@njit
def speed_chunk(start, length, mgxs, data):
    start += mgxs["speed_offset"]
    end = start + length
    return data[start:end]


@njit
def decay_rate(index, mgxs, data):
    offset = mgxs["decay_rate_offset"]
    return data[offset + index]


@njit
def decay_rate_all(mgxs, data):
    start = mgxs["decay_rate_offset"]
    size = mgxs["J"]
    end = start + size
    return data[start:end]


@njit
def decay_rate_last(mgxs, data):
    start = mgxs["decay_rate_offset"]
    size = mgxs["J"]
    end = start + size
    return data[end - 1]


@njit
def decay_rate_chunk(start, length, mgxs, data):
    start += mgxs["decay_rate_offset"]
    end = start + length
    return data[start:end]


@njit
def capture(index, mgxs, data):
    offset = mgxs["capture_offset"]
    return data[offset + index]


@njit
def capture_all(mgxs, data):
    start = mgxs["capture_offset"]
    size = mgxs["G"]
    end = start + size
    return data[start:end]


@njit
def capture_last(mgxs, data):
    start = mgxs["capture_offset"]
    size = mgxs["G"]
    end = start + size
    return data[end - 1]


@njit
def capture_chunk(start, length, mgxs, data):
    start += mgxs["capture_offset"]
    end = start + length
    return data[start:end]


@njit
def scatter(index, mgxs, data):
    offset = mgxs["scatter_offset"]
    return data[offset + index]


@njit
def scatter_all(mgxs, data):
    start = mgxs["scatter_offset"]
    size = mgxs["G"]
    end = start + size
    return data[start:end]


@njit
def scatter_last(mgxs, data):
    start = mgxs["scatter_offset"]
    size = mgxs["G"]
    end = start + size
    return data[end - 1]


@njit
def scatter_chunk(start, length, mgxs, data):
    start += mgxs["scatter_offset"]
    end = start + length
    return data[start:end]


@njit
def fission(index, mgxs, data):
    offset = mgxs["fission_offset"]
    return data[offset + index]


@njit
def fission_all(mgxs, data):
    start = mgxs["fission_offset"]
    size = mgxs["G"]
    end = start + size
    return data[start:end]


@njit
def fission_last(mgxs, data):
    start = mgxs["fission_offset"]
    size = mgxs["G"]
    end = start + size
    return data[end - 1]


@njit
def fission_chunk(start, length, mgxs, data):
    start += mgxs["fission_offset"]
    end = start + length
    return data[start:end]


@njit
def total(index, mgxs, data):
    offset = mgxs["total_offset"]
    return data[offset + index]


@njit
def total_all(mgxs, data):
    start = mgxs["total_offset"]
    size = mgxs["G"]
    end = start + size
    return data[start:end]


@njit
def total_last(mgxs, data):
    start = mgxs["total_offset"]
    size = mgxs["G"]
    end = start + size
    return data[end - 1]


@njit
def total_chunk(start, length, mgxs, data):
    start += mgxs["total_offset"]
    end = start + length
    return data[start:end]


@njit
def nu_s(index, mgxs, data):
    offset = mgxs["nu_s_offset"]
    return data[offset + index]


@njit
def nu_s_all(mgxs, data):
    start = mgxs["nu_s_offset"]
    size = mgxs["G"]
    end = start + size
    return data[start:end]


@njit
def nu_s_last(mgxs, data):
    start = mgxs["nu_s_offset"]
    size = mgxs["G"]
    end = start + size
    return data[end - 1]


@njit
def nu_s_chunk(start, length, mgxs, data):
    start += mgxs["nu_s_offset"]
    end = start + length
    return data[start:end]


@njit
def nu_p(index, mgxs, data):
    offset = mgxs["nu_p_offset"]
    return data[offset + index]


@njit
def nu_p_all(mgxs, data):
    start = mgxs["nu_p_offset"]
    size = mgxs["G"]
    end = start + size
    return data[start:end]


@njit
def nu_p_last(mgxs, data):
    start = mgxs["nu_p_offset"]
    size = mgxs["G"]
    end = start + size
    return data[end - 1]


@njit
def nu_p_chunk(start, length, mgxs, data):
    start += mgxs["nu_p_offset"]
    end = start + length
    return data[start:end]


@njit
def nu_d_vector(index_1, mgxs, data):
    offset = mgxs["nu_d_offset"]
    stride = mgxs["J"]
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def nu_d(index_1, index_2, mgxs, data):
    offset = mgxs["nu_d_offset"]
    stride = mgxs["J"]
    return data[offset + index_1 * stride + index_2]


@njit
def nu_d_chunk(start, length, mgxs, data):
    start += mgxs["nu_d_offset"]
    end = start + length
    return data[start:end]


@njit
def nu_d_total(index, mgxs, data):
    offset = mgxs["nu_d_total_offset"]
    return data[offset + index]


@njit
def nu_d_total_all(mgxs, data):
    start = mgxs["nu_d_total_offset"]
    size = mgxs["G"]
    end = start + size
    return data[start:end]


@njit
def nu_d_total_last(mgxs, data):
    start = mgxs["nu_d_total_offset"]
    size = mgxs["G"]
    end = start + size
    return data[end - 1]


@njit
def nu_d_total_chunk(start, length, mgxs, data):
    start += mgxs["nu_d_total_offset"]
    end = start + length
    return data[start:end]


@njit
def nu_f(index, mgxs, data):
    offset = mgxs["nu_f_offset"]
    return data[offset + index]


@njit
def nu_f_all(mgxs, data):
    start = mgxs["nu_f_offset"]
    size = mgxs["G"]
    end = start + size
    return data[start:end]


@njit
def nu_f_last(mgxs, data):
    start = mgxs["nu_f_offset"]
    size = mgxs["G"]
    end = start + size
    return data[end - 1]


@njit
def nu_f_chunk(start, length, mgxs, data):
    start += mgxs["nu_f_offset"]
    end = start + length
    return data[start:end]


@njit
def chi_s_vector(index_1, mgxs, data):
    offset = mgxs["chi_s_offset"]
    stride = mgxs["G"]
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def chi_s(index_1, index_2, mgxs, data):
    offset = mgxs["chi_s_offset"]
    stride = mgxs["G"]
    return data[offset + index_1 * stride + index_2]


@njit
def chi_s_chunk(start, length, mgxs, data):
    start += mgxs["chi_s_offset"]
    end = start + length
    return data[start:end]


@njit
def chi_p_vector(index_1, mgxs, data):
    offset = mgxs["chi_p_offset"]
    stride = mgxs["G"]
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def chi_p(index_1, index_2, mgxs, data):
    offset = mgxs["chi_p_offset"]
    stride = mgxs["G"]
    return data[offset + index_1 * stride + index_2]


@njit
def chi_p_chunk(start, length, mgxs, data):
    start += mgxs["chi_p_offset"]
    end = start + length
    return data[start:end]


@njit
def chi_d_vector(index_1, mgxs, data):
    offset = mgxs["chi_d_offset"]
    stride = mgxs["G"]
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def chi_d(index_1, index_2, mgxs, data):
    offset = mgxs["chi_d_offset"]
    stride = mgxs["G"]
    return data[offset + index_1 * stride + index_2]


@njit
def chi_d_chunk(start, length, mgxs, data):
    start += mgxs["chi_d_offset"]
    end = start + length
    return data[start:end]
