# The following is automatically generated by code_factory.py

from numpy import int64
from numba import njit


@njit
def nuclide_IDs(index, native_material, data):
    offset = native_material["nuclide_IDs_offset"]
    return int64(data[offset + index])


@njit
def nuclide_IDs_all(native_material, data):
    start = native_material["nuclide_IDs_offset"]
    size = native_material["N_nuclide"]
    end = start + size
    return data[start:end]


@njit
def nuclide_IDs_last(native_material, data):
    start = native_material["nuclide_IDs_offset"]
    size = native_material["N_nuclide"]
    end = start + size
    return int64(data[end - 1])


@njit
def nuclide_IDs_chunk(start, length, native_material, data):
    start += native_material["nuclide_IDs_offset"]
    end = start + length
    return data[start:end]


@njit
def element_IDs(index, native_material, data):
    offset = native_material["element_IDs_offset"]
    return int64(data[offset + index])


@njit
def element_IDs_all(native_material, data):
    start = native_material["element_IDs_offset"]
    size = native_material["N_element"]
    end = start + size
    return data[start:end]


@njit
def element_IDs_last(native_material, data):
    start = native_material["element_IDs_offset"]
    size = native_material["N_element"]
    end = start + size
    return int64(data[end - 1])


@njit
def element_IDs_chunk(start, length, native_material, data):
    start += native_material["element_IDs_offset"]
    end = start + length
    return data[start:end]


@njit
def nuclide_densities(index, native_material, data):
    offset = native_material["nuclide_densities_offset"]
    return data[offset + index]


@njit
def nuclide_densities_all(native_material, data):
    start = native_material["nuclide_densities_offset"]
    size = native_material["nuclide_densities_length"]
    end = start + size
    return data[start:end]


@njit
def nuclide_densities_last(native_material, data):
    start = native_material["nuclide_densities_offset"]
    size = native_material["nuclide_densities_length"]
    end = start + size
    return data[end - 1]


@njit
def nuclide_densities_chunk(start, length, native_material, data):
    start += native_material["nuclide_densities_offset"]
    end = start + length
    return data[start:end]


@njit
def element_densities(index, native_material, data):
    offset = native_material["element_densities_offset"]
    return data[offset + index]


@njit
def element_densities_all(native_material, data):
    start = native_material["element_densities_offset"]
    size = native_material["element_densities_length"]
    end = start + size
    return data[start:end]


@njit
def element_densities_last(native_material, data):
    start = native_material["element_densities_offset"]
    size = native_material["element_densities_length"]
    end = start + size
    return data[end - 1]


@njit
def element_densities_chunk(start, length, native_material, data):
    start += native_material["element_densities_offset"]
    end = start + length
    return data[start:end]
