# The following is automatically generated by code_factory.py

from numba import njit


@njit
def energy_grid(index, neutron_multigroup, data):
    offset = neutron_multigroup["energy_grid_offset"]
    return data[offset + index]


@njit
def energy_grid_all(neutron_multigroup, data):
    start = neutron_multigroup["energy_grid_offset"]
    size = neutron_multigroup["G"] + 1
    end = start + size
    return data[start:end]


@njit
def energy_grid_last(neutron_multigroup, data):
    start = neutron_multigroup["energy_grid_offset"]
    size = neutron_multigroup["G"] + 1
    end = start + size
    return data[end - 1]


@njit
def energy_grid_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["energy_grid_offset"]
    end = start + length
    return data[start:end]


@njit
def speed(index, neutron_multigroup, data):
    offset = neutron_multigroup["speed_offset"]
    return data[offset + index]


@njit
def speed_all(neutron_multigroup, data):
    start = neutron_multigroup["speed_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[start:end]


@njit
def speed_last(neutron_multigroup, data):
    start = neutron_multigroup["speed_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[end - 1]


@njit
def speed_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["speed_offset"]
    end = start + length
    return data[start:end]


@njit
def decay_rate(index, neutron_multigroup, data):
    offset = neutron_multigroup["decay_rate_offset"]
    return data[offset + index]


@njit
def decay_rate_all(neutron_multigroup, data):
    start = neutron_multigroup["decay_rate_offset"]
    size = neutron_multigroup["J"]
    end = start + size
    return data[start:end]


@njit
def decay_rate_last(neutron_multigroup, data):
    start = neutron_multigroup["decay_rate_offset"]
    size = neutron_multigroup["J"]
    end = start + size
    return data[end - 1]


@njit
def decay_rate_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["decay_rate_offset"]
    end = start + length
    return data[start:end]


@njit
def capture(index, neutron_multigroup, data):
    offset = neutron_multigroup["capture_offset"]
    return data[offset + index]


@njit
def capture_all(neutron_multigroup, data):
    start = neutron_multigroup["capture_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[start:end]


@njit
def capture_last(neutron_multigroup, data):
    start = neutron_multigroup["capture_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[end - 1]


@njit
def capture_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["capture_offset"]
    end = start + length
    return data[start:end]


@njit
def scatter(index, neutron_multigroup, data):
    offset = neutron_multigroup["scatter_offset"]
    return data[offset + index]


@njit
def scatter_all(neutron_multigroup, data):
    start = neutron_multigroup["scatter_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[start:end]


@njit
def scatter_last(neutron_multigroup, data):
    start = neutron_multigroup["scatter_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[end - 1]


@njit
def scatter_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["scatter_offset"]
    end = start + length
    return data[start:end]


@njit
def fission(index, neutron_multigroup, data):
    offset = neutron_multigroup["fission_offset"]
    return data[offset + index]


@njit
def fission_all(neutron_multigroup, data):
    start = neutron_multigroup["fission_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[start:end]


@njit
def fission_last(neutron_multigroup, data):
    start = neutron_multigroup["fission_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[end - 1]


@njit
def fission_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["fission_offset"]
    end = start + length
    return data[start:end]


@njit
def total(index, neutron_multigroup, data):
    offset = neutron_multigroup["total_offset"]
    return data[offset + index]


@njit
def total_all(neutron_multigroup, data):
    start = neutron_multigroup["total_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[start:end]


@njit
def total_last(neutron_multigroup, data):
    start = neutron_multigroup["total_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[end - 1]


@njit
def total_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["total_offset"]
    end = start + length
    return data[start:end]


@njit
def nu_s(index, neutron_multigroup, data):
    offset = neutron_multigroup["nu_s_offset"]
    return data[offset + index]


@njit
def nu_s_all(neutron_multigroup, data):
    start = neutron_multigroup["nu_s_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[start:end]


@njit
def nu_s_last(neutron_multigroup, data):
    start = neutron_multigroup["nu_s_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[end - 1]


@njit
def nu_s_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["nu_s_offset"]
    end = start + length
    return data[start:end]


@njit
def nu_p(index, neutron_multigroup, data):
    offset = neutron_multigroup["nu_p_offset"]
    return data[offset + index]


@njit
def nu_p_all(neutron_multigroup, data):
    start = neutron_multigroup["nu_p_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[start:end]


@njit
def nu_p_last(neutron_multigroup, data):
    start = neutron_multigroup["nu_p_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[end - 1]


@njit
def nu_p_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["nu_p_offset"]
    end = start + length
    return data[start:end]


@njit
def nu_d_vector(index_1, neutron_multigroup, data):
    offset = neutron_multigroup["nu_d_offset"]
    stride = neutron_multigroup["J"]
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def nu_d(index_1, index_2, neutron_multigroup, data):
    offset = neutron_multigroup["nu_d_offset"]
    stride = neutron_multigroup["J"]
    return data[offset + index_1 * stride + index_2]


@njit
def nu_d_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["nu_d_offset"]
    end = start + length
    return data[start:end]


@njit
def nu_d_total(index, neutron_multigroup, data):
    offset = neutron_multigroup["nu_d_total_offset"]
    return data[offset + index]


@njit
def nu_d_total_all(neutron_multigroup, data):
    start = neutron_multigroup["nu_d_total_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[start:end]


@njit
def nu_d_total_last(neutron_multigroup, data):
    start = neutron_multigroup["nu_d_total_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[end - 1]


@njit
def nu_d_total_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["nu_d_total_offset"]
    end = start + length
    return data[start:end]


@njit
def nu_f(index, neutron_multigroup, data):
    offset = neutron_multigroup["nu_f_offset"]
    return data[offset + index]


@njit
def nu_f_all(neutron_multigroup, data):
    start = neutron_multigroup["nu_f_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[start:end]


@njit
def nu_f_last(neutron_multigroup, data):
    start = neutron_multigroup["nu_f_offset"]
    size = neutron_multigroup["G"]
    end = start + size
    return data[end - 1]


@njit
def nu_f_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["nu_f_offset"]
    end = start + length
    return data[start:end]


@njit
def chi_s_vector(index_1, neutron_multigroup, data):
    offset = neutron_multigroup["chi_s_offset"]
    stride = neutron_multigroup["G"]
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def chi_s(index_1, index_2, neutron_multigroup, data):
    offset = neutron_multigroup["chi_s_offset"]
    stride = neutron_multigroup["G"]
    return data[offset + index_1 * stride + index_2]


@njit
def chi_s_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["chi_s_offset"]
    end = start + length
    return data[start:end]


@njit
def chi_p_vector(index_1, neutron_multigroup, data):
    offset = neutron_multigroup["chi_p_offset"]
    stride = neutron_multigroup["G"]
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def chi_p(index_1, index_2, neutron_multigroup, data):
    offset = neutron_multigroup["chi_p_offset"]
    stride = neutron_multigroup["G"]
    return data[offset + index_1 * stride + index_2]


@njit
def chi_p_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["chi_p_offset"]
    end = start + length
    return data[start:end]


@njit
def chi_d_vector(index_1, neutron_multigroup, data):
    offset = neutron_multigroup["chi_d_offset"]
    stride = neutron_multigroup["G"]
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def chi_d(index_1, index_2, neutron_multigroup, data):
    offset = neutron_multigroup["chi_d_offset"]
    stride = neutron_multigroup["G"]
    return data[offset + index_1 * stride + index_2]


@njit
def chi_d_chunk(start, length, neutron_multigroup, data):
    start += neutron_multigroup["chi_d_offset"]
    end = start + length
    return data[start:end]
