# The following is automatically generated by code_factory.py

from numpy import int64
from numba import njit


@njit
def spectrum_probability_grid(index, neutron_inelastic_scattering_reaction, data):
    offset = neutron_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    return data[offset + index]


@njit
def spectrum_probability_grid_all(neutron_inelastic_scattering_reaction, data):
    start = neutron_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    size = neutron_inelastic_scattering_reaction["spectrum_probability_grid_length"]
    end = start + size
    return data[start:end]


@njit
def spectrum_probability_grid_last(neutron_inelastic_scattering_reaction, data):
    start = neutron_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    size = neutron_inelastic_scattering_reaction["spectrum_probability_grid_length"]
    end = start + size
    return data[end - 1]


@njit
def spectrum_probability_grid_chunk(start, length, neutron_inelastic_scattering_reaction, data):
    start += neutron_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    end = start + length
    return data[start:end]


@njit
def spectrum_probability_vector(index_1, neutron_inelastic_scattering_reaction, data):
    offset = neutron_inelastic_scattering_reaction["spectrum_probability_offset"]
    stride = neutron_inelastic_scattering_reaction["N_spectrum"]
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def spectrum_probability(index_1, index_2, neutron_inelastic_scattering_reaction, data):
    offset = neutron_inelastic_scattering_reaction["spectrum_probability_offset"]
    stride = neutron_inelastic_scattering_reaction["N_spectrum"]
    return data[offset + index_1 * stride + index_2]


@njit
def spectrum_probability_chunk(start, length, neutron_inelastic_scattering_reaction, data):
    start += neutron_inelastic_scattering_reaction["spectrum_probability_offset"]
    end = start + length
    return data[start:end]


@njit
def energy_spectrum_IDs(index, neutron_inelastic_scattering_reaction, data):
    offset = neutron_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    return int64(data[offset + index])


@njit
def energy_spectrum_IDs_all(neutron_inelastic_scattering_reaction, data):
    start = neutron_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    size = neutron_inelastic_scattering_reaction["N_energy_spectrum"]
    end = start + size
    return data[start:end]


@njit
def energy_spectrum_IDs_last(neutron_inelastic_scattering_reaction, data):
    start = neutron_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    size = neutron_inelastic_scattering_reaction["N_energy_spectrum"]
    end = start + size
    return int64(data[end - 1])


@njit
def energy_spectrum_IDs_chunk(start, length, neutron_inelastic_scattering_reaction, data):
    start += neutron_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    end = start + length
    return data[start:end]
