# The following is automatically generated by code_factory.py

from numba import njit


@njit
def move_velocities_vector(index_1, surface, data):
    offset = surface["move_velocities_offset"]
    stride = 3
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def move_velocities(index_1, index_2, surface, data):
    offset = surface["move_velocities_offset"]
    stride = 3
    return data[offset + index_1 * stride + index_2]


@njit
def move_velocities_chunk(start, length, surface, data):
    start += surface["move_velocities_offset"]
    end = start + length
    return data[start:end]


@njit
def move_durations(index, surface, data):
    offset = surface["move_durations_offset"]
    return data[offset + index]


@njit
def move_durations_all(surface, data):
    start = surface["move_durations_offset"]
    size = surface["N_move"]
    end = start + size
    return data[start:end]


@njit
def move_durations_last(surface, data):
    start = surface["move_durations_offset"]
    size = surface["N_move"]
    end = start + size
    return data[end - 1]


@njit
def move_durations_chunk(start, length, surface, data):
    start += surface["move_durations_offset"]
    end = start + length
    return data[start:end]


@njit
def move_time_grid(index, surface, data):
    offset = surface["move_time_grid_offset"]
    return data[offset + index]


@njit
def move_time_grid_all(surface, data):
    start = surface["move_time_grid_offset"]
    size = surface["N_move_grid"]
    end = start + size
    return data[start:end]


@njit
def move_time_grid_last(surface, data):
    start = surface["move_time_grid_offset"]
    size = surface["N_move_grid"]
    end = start + size
    return data[end - 1]


@njit
def move_time_grid_chunk(start, length, surface, data):
    start += surface["move_time_grid_offset"]
    end = start + length
    return data[start:end]


@njit
def move_translations_vector(index_1, surface, data):
    offset = surface["move_translations_offset"]
    stride = 3
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def move_translations(index_1, index_2, surface, data):
    offset = surface["move_translations_offset"]
    stride = 3
    return data[offset + index_1 * stride + index_2]


@njit
def move_translations_chunk(start, length, surface, data):
    start += surface["move_translations_offset"]
    end = start + length
    return data[start:end]


@njit
def surface_crossing_tally_IDs(index, surface, data):
    offset = surface["surface_crossing_tally_IDs_offset"]
    return data[offset + index]


@njit
def surface_crossing_tally_IDs_all(surface, data):
    start = surface["surface_crossing_tally_IDs_offset"]
    size = surface["N_surface_crossing_tally"]
    end = start + size
    return data[start:end]


@njit
def surface_crossing_tally_IDs_last(surface, data):
    start = surface["surface_crossing_tally_IDs_offset"]
    size = surface["N_surface_crossing_tally"]
    end = start + size
    return data[end - 1]


@njit
def surface_crossing_tally_IDs_chunk(start, length, surface, data):
    start += surface["surface_crossing_tally_IDs_offset"]
    end = start + length
    return data[start:end]
