# The following is automatically generated by code_factory.py

from numpy import int64
from numba import njit


@njit
def x(index, table_data, data):
    offset = table_data["x_offset"]
    return data[offset + index]


@njit
def x_all(table_data, data):
    start = table_data["x_offset"]
    size = table_data["x_length"]
    end = start + size
    return data[start:end]


@njit
def x_last(table_data, data):
    start = table_data["x_offset"]
    size = table_data["x_length"]
    end = start + size
    return data[end - 1]


@njit
def x_chunk(start, length, table_data, data):
    start += table_data["x_offset"]
    end = start + length
    return data[start:end]


@njit
def y(index, table_data, data):
    offset = table_data["y_offset"]
    return data[offset + index]


@njit
def y_all(table_data, data):
    start = table_data["y_offset"]
    size = table_data["y_length"]
    end = start + size
    return data[start:end]


@njit
def y_last(table_data, data):
    start = table_data["y_offset"]
    size = table_data["y_length"]
    end = start + size
    return data[end - 1]


@njit
def y_chunk(start, length, table_data, data):
    start += table_data["y_offset"]
    end = start + length
    return data[start:end]


@njit
def interpolations(index, table_data, data):
    offset = table_data["interpolations_offset"]
    return int64(data[offset + index])


@njit
def interpolations_all(table_data, data):
    start = table_data["interpolations_offset"]
    size = table_data["interpolations_length"]
    end = start + size
    return data[start:end]


@njit
def interpolations_last(table_data, data):
    start = table_data["interpolations_offset"]
    size = table_data["interpolations_length"]
    end = start + size
    return int64(data[end - 1])


@njit
def interpolations_chunk(start, length, table_data, data):
    start += table_data["interpolations_offset"]
    end = start + length
    return data[start:end]


@njit
def interpolation_boundaries(index, table_data, data):
    offset = table_data["interpolation_boundaries_offset"]
    return int64(data[offset + index])


@njit
def interpolation_boundaries_all(table_data, data):
    start = table_data["interpolation_boundaries_offset"]
    size = table_data["interpolation_boundaries_length"]
    end = start + size
    return data[start:end]


@njit
def interpolation_boundaries_last(table_data, data):
    start = table_data["interpolation_boundaries_offset"]
    size = table_data["interpolation_boundaries_length"]
    end = start + size
    return int64(data[end - 1])


@njit
def interpolation_boundaries_chunk(start, length, table_data, data):
    start += table_data["interpolation_boundaries_offset"]
    end = start + length
    return data[start:end]


@njit
def aux_vector(index_1, table_data, data):
    offset = table_data["aux_offset"]
    stride = table_data["N"]
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def aux(index_1, index_2, table_data, data):
    offset = table_data["aux_offset"]
    stride = table_data["N"]
    return data[offset + index_1 * stride + index_2]


@njit
def aux_chunk(start, length, table_data, data):
    start += table_data["aux_offset"]
    end = start + length
    return data[start:end]
