# The following is automatically generated by code_factory.py

from numpy import int64
from numba import njit


@njit
def energy(index, tabulated_energy_angle_distribution, data):
    offset = tabulated_energy_angle_distribution["energy_offset"]
    return data[offset + index]


@njit
def energy_all(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["energy_offset"]
    size = tabulated_energy_angle_distribution["energy_length"]
    end = start + size
    return data[start:end]


@njit
def energy_last(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["energy_offset"]
    size = tabulated_energy_angle_distribution["energy_length"]
    end = start + size
    return data[end - 1]


@njit
def energy_chunk(start, length, tabulated_energy_angle_distribution, data):
    start += tabulated_energy_angle_distribution["energy_offset"]
    end = start + length
    return data[start:end]


@njit
def offset(index, tabulated_energy_angle_distribution, data):
    offset = tabulated_energy_angle_distribution["offset_offset"]
    return int64(data[offset + index])


@njit
def offset_all(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["offset_offset"]
    size = tabulated_energy_angle_distribution["offset_length"]
    end = start + size
    return data[start:end]


@njit
def offset_last(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["offset_offset"]
    size = tabulated_energy_angle_distribution["offset_length"]
    end = start + size
    return int64(data[end - 1])


@njit
def offset_chunk(start, length, tabulated_energy_angle_distribution, data):
    start += tabulated_energy_angle_distribution["offset_offset"]
    end = start + length
    return data[start:end]


@njit
def energy_out(index, tabulated_energy_angle_distribution, data):
    offset = tabulated_energy_angle_distribution["energy_out_offset"]
    return data[offset + index]


@njit
def energy_out_all(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["energy_out_offset"]
    size = tabulated_energy_angle_distribution["energy_out_length"]
    end = start + size
    return data[start:end]


@njit
def energy_out_last(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["energy_out_offset"]
    size = tabulated_energy_angle_distribution["energy_out_length"]
    end = start + size
    return data[end - 1]


@njit
def energy_out_chunk(start, length, tabulated_energy_angle_distribution, data):
    start += tabulated_energy_angle_distribution["energy_out_offset"]
    end = start + length
    return data[start:end]


@njit
def pdf(index, tabulated_energy_angle_distribution, data):
    offset = tabulated_energy_angle_distribution["pdf_offset"]
    return data[offset + index]


@njit
def pdf_all(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["pdf_offset"]
    size = tabulated_energy_angle_distribution["pdf_length"]
    end = start + size
    return data[start:end]


@njit
def pdf_last(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["pdf_offset"]
    size = tabulated_energy_angle_distribution["pdf_length"]
    end = start + size
    return data[end - 1]


@njit
def pdf_chunk(start, length, tabulated_energy_angle_distribution, data):
    start += tabulated_energy_angle_distribution["pdf_offset"]
    end = start + length
    return data[start:end]


@njit
def cdf(index, tabulated_energy_angle_distribution, data):
    offset = tabulated_energy_angle_distribution["cdf_offset"]
    return data[offset + index]


@njit
def cdf_all(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["cdf_offset"]
    size = tabulated_energy_angle_distribution["cdf_length"]
    end = start + size
    return data[start:end]


@njit
def cdf_last(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["cdf_offset"]
    size = tabulated_energy_angle_distribution["cdf_length"]
    end = start + size
    return data[end - 1]


@njit
def cdf_chunk(start, length, tabulated_energy_angle_distribution, data):
    start += tabulated_energy_angle_distribution["cdf_offset"]
    end = start + length
    return data[start:end]


@njit
def cosine_offset_(index, tabulated_energy_angle_distribution, data):
    offset = tabulated_energy_angle_distribution["cosine_offset__offset"]
    return int64(data[offset + index])


@njit
def cosine_offset__all(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["cosine_offset__offset"]
    size = tabulated_energy_angle_distribution["cosine_offset__length"]
    end = start + size
    return data[start:end]


@njit
def cosine_offset__last(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["cosine_offset__offset"]
    size = tabulated_energy_angle_distribution["cosine_offset__length"]
    end = start + size
    return int64(data[end - 1])


@njit
def cosine_offset__chunk(start, length, tabulated_energy_angle_distribution, data):
    start += tabulated_energy_angle_distribution["cosine_offset__offset"]
    end = start + length
    return data[start:end]


@njit
def cosine(index, tabulated_energy_angle_distribution, data):
    offset = tabulated_energy_angle_distribution["cosine_offset"]
    return data[offset + index]


@njit
def cosine_all(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["cosine_offset"]
    size = tabulated_energy_angle_distribution["cosine_length"]
    end = start + size
    return data[start:end]


@njit
def cosine_last(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["cosine_offset"]
    size = tabulated_energy_angle_distribution["cosine_length"]
    end = start + size
    return data[end - 1]


@njit
def cosine_chunk(start, length, tabulated_energy_angle_distribution, data):
    start += tabulated_energy_angle_distribution["cosine_offset"]
    end = start + length
    return data[start:end]


@njit
def cosine_pdf(index, tabulated_energy_angle_distribution, data):
    offset = tabulated_energy_angle_distribution["cosine_pdf_offset"]
    return data[offset + index]


@njit
def cosine_pdf_all(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["cosine_pdf_offset"]
    size = tabulated_energy_angle_distribution["cosine_pdf_length"]
    end = start + size
    return data[start:end]


@njit
def cosine_pdf_last(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["cosine_pdf_offset"]
    size = tabulated_energy_angle_distribution["cosine_pdf_length"]
    end = start + size
    return data[end - 1]


@njit
def cosine_pdf_chunk(start, length, tabulated_energy_angle_distribution, data):
    start += tabulated_energy_angle_distribution["cosine_pdf_offset"]
    end = start + length
    return data[start:end]


@njit
def cosine_cdf(index, tabulated_energy_angle_distribution, data):
    offset = tabulated_energy_angle_distribution["cosine_cdf_offset"]
    return data[offset + index]


@njit
def cosine_cdf_all(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["cosine_cdf_offset"]
    size = tabulated_energy_angle_distribution["cosine_cdf_length"]
    end = start + size
    return data[start:end]


@njit
def cosine_cdf_last(tabulated_energy_angle_distribution, data):
    start = tabulated_energy_angle_distribution["cosine_cdf_offset"]
    size = tabulated_energy_angle_distribution["cosine_cdf_length"]
    end = start + size
    return data[end - 1]


@njit
def cosine_cdf_chunk(start, length, tabulated_energy_angle_distribution, data):
    start += tabulated_energy_angle_distribution["cosine_cdf_offset"]
    end = start + length
    return data[start:end]
