# The following is automatically generated by code_factory.py

from numpy import int64
from numba import njit


@njit
def scores(index, tally, data):
    offset = tally["scores_offset"]
    return int64(data[offset + index])


@njit
def scores_all(tally, data):
    start = tally["scores_offset"]
    size = tally["scores_length"]
    end = start + size
    return data[start:end]


@njit
def scores_last(tally, data):
    start = tally["scores_offset"]
    size = tally["scores_length"]
    end = start + size
    return int64(data[end - 1])


@njit
def scores_chunk(start, length, tally, data):
    start += tally["scores_offset"]
    end = start + length
    return data[start:end]


@njit
def mu(index, tally, data):
    offset = tally["mu_offset"]
    return data[offset + index]


@njit
def mu_all(tally, data):
    start = tally["mu_offset"]
    size = tally["mu_length"]
    end = start + size
    return data[start:end]


@njit
def mu_last(tally, data):
    start = tally["mu_offset"]
    size = tally["mu_length"]
    end = start + size
    return data[end - 1]


@njit
def mu_chunk(start, length, tally, data):
    start += tally["mu_offset"]
    end = start + length
    return data[start:end]


@njit
def azi(index, tally, data):
    offset = tally["azi_offset"]
    return data[offset + index]


@njit
def azi_all(tally, data):
    start = tally["azi_offset"]
    size = tally["azi_length"]
    end = start + size
    return data[start:end]


@njit
def azi_last(tally, data):
    start = tally["azi_offset"]
    size = tally["azi_length"]
    end = start + size
    return data[end - 1]


@njit
def azi_chunk(start, length, tally, data):
    start += tally["azi_offset"]
    end = start + length
    return data[start:end]


@njit
def group(index, tally, data):
    offset = tally["group_offset"]
    return data[offset + index]


@njit
def group_all(tally, data):
    start = tally["group_offset"]
    size = tally["group_length"]
    end = start + size
    return data[start:end]


@njit
def group_last(tally, data):
    start = tally["group_offset"]
    size = tally["group_length"]
    end = start + size
    return data[end - 1]


@njit
def group_chunk(start, length, tally, data):
    start += tally["group_offset"]
    end = start + length
    return data[start:end]


@njit
def energy(index, tally, data):
    offset = tally["energy_offset"]
    return data[offset + index]


@njit
def energy_all(tally, data):
    start = tally["energy_offset"]
    size = tally["energy_length"]
    end = start + size
    return data[start:end]


@njit
def energy_last(tally, data):
    start = tally["energy_offset"]
    size = tally["energy_length"]
    end = start + size
    return data[end - 1]


@njit
def energy_chunk(start, length, tally, data):
    start += tally["energy_offset"]
    end = start + length
    return data[start:end]


@njit
def time(index, tally, data):
    offset = tally["time_offset"]
    return data[offset + index]


@njit
def time_all(tally, data):
    start = tally["time_offset"]
    size = tally["time_length"]
    end = start + size
    return data[start:end]


@njit
def time_last(tally, data):
    start = tally["time_offset"]
    size = tally["time_length"]
    end = start + size
    return data[end - 1]


@njit
def time_chunk(start, length, tally, data):
    start += tally["time_offset"]
    end = start + length
    return data[start:end]


@njit
def bin(index, tally, data):
    offset = tally["bin_offset"]
    return data[offset + index]


@njit
def bin_all(tally, data):
    start = tally["bin_offset"]
    size = tally["bin_length"]
    end = start + size
    return data[start:end]


@njit
def bin_last(tally, data):
    start = tally["bin_offset"]
    size = tally["bin_length"]
    end = start + size
    return data[end - 1]


@njit
def bin_chunk(start, length, tally, data):
    start += tally["bin_offset"]
    end = start + length
    return data[start:end]


@njit
def bin_sum(index, tally, data):
    offset = tally["bin_sum_offset"]
    return data[offset + index]


@njit
def bin_sum_all(tally, data):
    start = tally["bin_sum_offset"]
    size = tally["bin_sum_length"]
    end = start + size
    return data[start:end]


@njit
def bin_sum_last(tally, data):
    start = tally["bin_sum_offset"]
    size = tally["bin_sum_length"]
    end = start + size
    return data[end - 1]


@njit
def bin_sum_chunk(start, length, tally, data):
    start += tally["bin_sum_offset"]
    end = start + length
    return data[start:end]


@njit
def bin_sum_square(index, tally, data):
    offset = tally["bin_sum_square_offset"]
    return data[offset + index]


@njit
def bin_sum_square_all(tally, data):
    start = tally["bin_sum_square_offset"]
    size = tally["bin_sum_square_length"]
    end = start + size
    return data[start:end]


@njit
def bin_sum_square_last(tally, data):
    start = tally["bin_sum_square_offset"]
    size = tally["bin_sum_square_length"]
    end = start + size
    return data[end - 1]


@njit
def bin_sum_square_chunk(start, length, tally, data):
    start += tally["bin_sum_square_offset"]
    end = start + length
    return data[start:end]


@njit
def bin_shape(index, tally, data):
    offset = tally["bin_shape_offset"]
    return int64(data[offset + index])


@njit
def bin_shape_all(tally, data):
    start = tally["bin_shape_offset"]
    size = tally["bin_shape_length"]
    end = start + size
    return data[start:end]


@njit
def bin_shape_last(tally, data):
    start = tally["bin_shape_offset"]
    size = tally["bin_shape_length"]
    end = start + size
    return int64(data[end - 1])


@njit
def bin_shape_chunk(start, length, tally, data):
    start += tally["bin_shape_offset"]
    end = start + length
    return data[start:end]
