# The following is automatically generated by code_factory.py

from numba import njit


@njit
def nuclide_IDs(index, material, data, value):
    offset = material["nuclide_IDs_offset"]
    data[offset + index] = value


@njit
def nuclide_IDs_all(material, data, value):
    start = material["nuclide_IDs_offset"]
    size = material["N_nuclide"]
    end = start + size
    data[start:end] = value


@njit
def nuclide_IDs_last(material, data, value):
    start = material["nuclide_IDs_offset"]
    size = material["N_nuclide"]
    end = start + size
    data[end - 1] = value


@njit
def nuclide_IDs_chunk(start, length, material, data, value):
    start += material["nuclide_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def element_IDs(index, material, data, value):
    offset = material["element_IDs_offset"]
    data[offset + index] = value


@njit
def element_IDs_all(material, data, value):
    start = material["element_IDs_offset"]
    size = material["N_element"]
    end = start + size
    data[start:end] = value


@njit
def element_IDs_last(material, data, value):
    start = material["element_IDs_offset"]
    size = material["N_element"]
    end = start + size
    data[end - 1] = value


@njit
def element_IDs_chunk(start, length, material, data, value):
    start += material["element_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def nuclide_densities(index, material, data, value):
    offset = material["nuclide_densities_offset"]
    data[offset + index] = value


@njit
def nuclide_densities_all(material, data, value):
    start = material["nuclide_densities_offset"]
    size = material["nuclide_densities_length"]
    end = start + size
    data[start:end] = value


@njit
def nuclide_densities_last(material, data, value):
    start = material["nuclide_densities_offset"]
    size = material["nuclide_densities_length"]
    end = start + size
    data[end - 1] = value


@njit
def nuclide_densities_chunk(start, length, material, data, value):
    start += material["nuclide_densities_offset"]
    end = start + length
    data[start:end] = value


@njit
def element_densities(index, material, data, value):
    offset = material["element_densities_offset"]
    data[offset + index] = value


@njit
def element_densities_all(material, data, value):
    start = material["element_densities_offset"]
    size = material["element_densities_length"]
    end = start + size
    data[start:end] = value


@njit
def element_densities_last(material, data, value):
    start = material["element_densities_offset"]
    size = material["element_densities_length"]
    end = start + size
    data[end - 1] = value


@njit
def element_densities_chunk(start, length, material, data, value):
    start += material["element_densities_offset"]
    end = start + length
    data[start:end] = value
