# The following is automatically generated by code_factory.py

from numba import njit


@njit
def mgxs_speed(index, multigroup_material, data, value):
    offset = multigroup_material["mgxs_speed_offset"]
    data[offset + index] = value


@njit
def mgxs_speed_all(multigroup_material, data, value):
    start = multigroup_material["mgxs_speed_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[start:end] = value


@njit
def mgxs_speed_last(multigroup_material, data, value):
    start = multigroup_material["mgxs_speed_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[end - 1] = value


@njit
def mgxs_speed_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_speed_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_decay_rate(index, multigroup_material, data, value):
    offset = multigroup_material["mgxs_decay_rate_offset"]
    data[offset + index] = value


@njit
def mgxs_decay_rate_all(multigroup_material, data, value):
    start = multigroup_material["mgxs_decay_rate_offset"]
    size = multigroup_material["J"]
    end = start + size
    data[start:end] = value


@njit
def mgxs_decay_rate_last(multigroup_material, data, value):
    start = multigroup_material["mgxs_decay_rate_offset"]
    size = multigroup_material["J"]
    end = start + size
    data[end - 1] = value


@njit
def mgxs_decay_rate_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_decay_rate_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_capture(index, multigroup_material, data, value):
    offset = multigroup_material["mgxs_capture_offset"]
    data[offset + index] = value


@njit
def mgxs_capture_all(multigroup_material, data, value):
    start = multigroup_material["mgxs_capture_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[start:end] = value


@njit
def mgxs_capture_last(multigroup_material, data, value):
    start = multigroup_material["mgxs_capture_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[end - 1] = value


@njit
def mgxs_capture_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_capture_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_scatter(index, multigroup_material, data, value):
    offset = multigroup_material["mgxs_scatter_offset"]
    data[offset + index] = value


@njit
def mgxs_scatter_all(multigroup_material, data, value):
    start = multigroup_material["mgxs_scatter_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[start:end] = value


@njit
def mgxs_scatter_last(multigroup_material, data, value):
    start = multigroup_material["mgxs_scatter_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[end - 1] = value


@njit
def mgxs_scatter_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_scatter_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_fission(index, multigroup_material, data, value):
    offset = multigroup_material["mgxs_fission_offset"]
    data[offset + index] = value


@njit
def mgxs_fission_all(multigroup_material, data, value):
    start = multigroup_material["mgxs_fission_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[start:end] = value


@njit
def mgxs_fission_last(multigroup_material, data, value):
    start = multigroup_material["mgxs_fission_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[end - 1] = value


@njit
def mgxs_fission_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_fission_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_total(index, multigroup_material, data, value):
    offset = multigroup_material["mgxs_total_offset"]
    data[offset + index] = value


@njit
def mgxs_total_all(multigroup_material, data, value):
    start = multigroup_material["mgxs_total_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[start:end] = value


@njit
def mgxs_total_last(multigroup_material, data, value):
    start = multigroup_material["mgxs_total_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[end - 1] = value


@njit
def mgxs_total_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_total_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_nu_s(index, multigroup_material, data, value):
    offset = multigroup_material["mgxs_nu_s_offset"]
    data[offset + index] = value


@njit
def mgxs_nu_s_all(multigroup_material, data, value):
    start = multigroup_material["mgxs_nu_s_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[start:end] = value


@njit
def mgxs_nu_s_last(multigroup_material, data, value):
    start = multigroup_material["mgxs_nu_s_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[end - 1] = value


@njit
def mgxs_nu_s_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_nu_s_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_nu_p(index, multigroup_material, data, value):
    offset = multigroup_material["mgxs_nu_p_offset"]
    data[offset + index] = value


@njit
def mgxs_nu_p_all(multigroup_material, data, value):
    start = multigroup_material["mgxs_nu_p_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[start:end] = value


@njit
def mgxs_nu_p_last(multigroup_material, data, value):
    start = multigroup_material["mgxs_nu_p_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[end - 1] = value


@njit
def mgxs_nu_p_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_nu_p_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_nu_d_vector(index_1, multigroup_material, data, value):
    offset = multigroup_material["mgxs_nu_d_offset"]
    stride = multigroup_material["J"]
    start = offset + index_1 * stride
    end = start + stride
    data[start:end] = value


@njit
def mgxs_nu_d(index_1, index_2, multigroup_material, data, value):
    offset = multigroup_material["mgxs_nu_d_offset"]
    stride = multigroup_material["J"]
    data[offset + index_1 * stride + index_2] = value


@njit
def mgxs_nu_d_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_nu_d_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_nu_d_total(index, multigroup_material, data, value):
    offset = multigroup_material["mgxs_nu_d_total_offset"]
    data[offset + index] = value


@njit
def mgxs_nu_d_total_all(multigroup_material, data, value):
    start = multigroup_material["mgxs_nu_d_total_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[start:end] = value


@njit
def mgxs_nu_d_total_last(multigroup_material, data, value):
    start = multigroup_material["mgxs_nu_d_total_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[end - 1] = value


@njit
def mgxs_nu_d_total_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_nu_d_total_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_nu_f(index, multigroup_material, data, value):
    offset = multigroup_material["mgxs_nu_f_offset"]
    data[offset + index] = value


@njit
def mgxs_nu_f_all(multigroup_material, data, value):
    start = multigroup_material["mgxs_nu_f_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[start:end] = value


@njit
def mgxs_nu_f_last(multigroup_material, data, value):
    start = multigroup_material["mgxs_nu_f_offset"]
    size = multigroup_material["G"]
    end = start + size
    data[end - 1] = value


@njit
def mgxs_nu_f_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_nu_f_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_chi_s_vector(index_1, multigroup_material, data, value):
    offset = multigroup_material["mgxs_chi_s_offset"]
    stride = multigroup_material["G"]
    start = offset + index_1 * stride
    end = start + stride
    data[start:end] = value


@njit
def mgxs_chi_s(index_1, index_2, multigroup_material, data, value):
    offset = multigroup_material["mgxs_chi_s_offset"]
    stride = multigroup_material["G"]
    data[offset + index_1 * stride + index_2] = value


@njit
def mgxs_chi_s_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_chi_s_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_chi_p_vector(index_1, multigroup_material, data, value):
    offset = multigroup_material["mgxs_chi_p_offset"]
    stride = multigroup_material["G"]
    start = offset + index_1 * stride
    end = start + stride
    data[start:end] = value


@njit
def mgxs_chi_p(index_1, index_2, multigroup_material, data, value):
    offset = multigroup_material["mgxs_chi_p_offset"]
    stride = multigroup_material["G"]
    data[offset + index_1 * stride + index_2] = value


@njit
def mgxs_chi_p_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_chi_p_offset"]
    end = start + length
    data[start:end] = value


@njit
def mgxs_chi_d_vector(index_1, multigroup_material, data, value):
    offset = multigroup_material["mgxs_chi_d_offset"]
    stride = multigroup_material["G"]
    start = offset + index_1 * stride
    end = start + stride
    data[start:end] = value


@njit
def mgxs_chi_d(index_1, index_2, multigroup_material, data, value):
    offset = multigroup_material["mgxs_chi_d_offset"]
    stride = multigroup_material["G"]
    data[offset + index_1 * stride + index_2] = value


@njit
def mgxs_chi_d_chunk(start, length, multigroup_material, data, value):
    start += multigroup_material["mgxs_chi_d_offset"]
    end = start + length
    data[start:end] = value
