# The following is automatically generated by code_factory.py

from numba import njit


@njit
def energy_grid(index, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["energy_grid_offset"]
    data[offset + index] = value


@njit
def energy_grid_all(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["energy_grid_offset"]
    size = neutron_multigroup_data["G"] + 1
    end = start + size
    data[start:end] = value


@njit
def energy_grid_last(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["energy_grid_offset"]
    size = neutron_multigroup_data["G"] + 1
    end = start + size
    data[end - 1] = value


@njit
def energy_grid_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["energy_grid_offset"]
    end = start + length
    data[start:end] = value


@njit
def speed(index, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["speed_offset"]
    data[offset + index] = value


@njit
def speed_all(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["speed_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[start:end] = value


@njit
def speed_last(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["speed_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[end - 1] = value


@njit
def speed_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["speed_offset"]
    end = start + length
    data[start:end] = value


@njit
def decay_rate(index, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["decay_rate_offset"]
    data[offset + index] = value


@njit
def decay_rate_all(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["decay_rate_offset"]
    size = neutron_multigroup_data["J"]
    end = start + size
    data[start:end] = value


@njit
def decay_rate_last(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["decay_rate_offset"]
    size = neutron_multigroup_data["J"]
    end = start + size
    data[end - 1] = value


@njit
def decay_rate_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["decay_rate_offset"]
    end = start + length
    data[start:end] = value


@njit
def capture(index, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["capture_offset"]
    data[offset + index] = value


@njit
def capture_all(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["capture_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[start:end] = value


@njit
def capture_last(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["capture_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[end - 1] = value


@njit
def capture_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["capture_offset"]
    end = start + length
    data[start:end] = value


@njit
def scatter(index, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["scatter_offset"]
    data[offset + index] = value


@njit
def scatter_all(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["scatter_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[start:end] = value


@njit
def scatter_last(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["scatter_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[end - 1] = value


@njit
def scatter_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["scatter_offset"]
    end = start + length
    data[start:end] = value


@njit
def fission(index, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["fission_offset"]
    data[offset + index] = value


@njit
def fission_all(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["fission_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[start:end] = value


@njit
def fission_last(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["fission_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[end - 1] = value


@njit
def fission_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["fission_offset"]
    end = start + length
    data[start:end] = value


@njit
def total(index, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["total_offset"]
    data[offset + index] = value


@njit
def total_all(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["total_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[start:end] = value


@njit
def total_last(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["total_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[end - 1] = value


@njit
def total_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["total_offset"]
    end = start + length
    data[start:end] = value


@njit
def nu_s(index, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["nu_s_offset"]
    data[offset + index] = value


@njit
def nu_s_all(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["nu_s_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[start:end] = value


@njit
def nu_s_last(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["nu_s_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[end - 1] = value


@njit
def nu_s_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["nu_s_offset"]
    end = start + length
    data[start:end] = value


@njit
def nu_p(index, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["nu_p_offset"]
    data[offset + index] = value


@njit
def nu_p_all(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["nu_p_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[start:end] = value


@njit
def nu_p_last(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["nu_p_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[end - 1] = value


@njit
def nu_p_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["nu_p_offset"]
    end = start + length
    data[start:end] = value


@njit
def nu_d_vector(index_1, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["nu_d_offset"]
    stride = neutron_multigroup_data["J"]
    start = offset + index_1 * stride
    end = start + stride
    data[start:end] = value


@njit
def nu_d(index_1, index_2, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["nu_d_offset"]
    stride = neutron_multigroup_data["J"]
    data[offset + index_1 * stride + index_2] = value


@njit
def nu_d_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["nu_d_offset"]
    end = start + length
    data[start:end] = value


@njit
def nu_d_total(index, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["nu_d_total_offset"]
    data[offset + index] = value


@njit
def nu_d_total_all(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["nu_d_total_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[start:end] = value


@njit
def nu_d_total_last(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["nu_d_total_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[end - 1] = value


@njit
def nu_d_total_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["nu_d_total_offset"]
    end = start + length
    data[start:end] = value


@njit
def nu_f(index, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["nu_f_offset"]
    data[offset + index] = value


@njit
def nu_f_all(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["nu_f_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[start:end] = value


@njit
def nu_f_last(neutron_multigroup_data, data, value):
    start = neutron_multigroup_data["nu_f_offset"]
    size = neutron_multigroup_data["G"]
    end = start + size
    data[end - 1] = value


@njit
def nu_f_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["nu_f_offset"]
    end = start + length
    data[start:end] = value


@njit
def chi_s_vector(index_1, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["chi_s_offset"]
    stride = neutron_multigroup_data["G"]
    start = offset + index_1 * stride
    end = start + stride
    data[start:end] = value


@njit
def chi_s(index_1, index_2, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["chi_s_offset"]
    stride = neutron_multigroup_data["G"]
    data[offset + index_1 * stride + index_2] = value


@njit
def chi_s_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["chi_s_offset"]
    end = start + length
    data[start:end] = value


@njit
def chi_p_vector(index_1, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["chi_p_offset"]
    stride = neutron_multigroup_data["G"]
    start = offset + index_1 * stride
    end = start + stride
    data[start:end] = value


@njit
def chi_p(index_1, index_2, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["chi_p_offset"]
    stride = neutron_multigroup_data["G"]
    data[offset + index_1 * stride + index_2] = value


@njit
def chi_p_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["chi_p_offset"]
    end = start + length
    data[start:end] = value


@njit
def chi_d_vector(index_1, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["chi_d_offset"]
    stride = neutron_multigroup_data["G"]
    start = offset + index_1 * stride
    end = start + stride
    data[start:end] = value


@njit
def chi_d(index_1, index_2, neutron_multigroup_data, data, value):
    offset = neutron_multigroup_data["chi_d_offset"]
    stride = neutron_multigroup_data["G"]
    data[offset + index_1 * stride + index_2] = value


@njit
def chi_d_chunk(start, length, neutron_multigroup_data, data, value):
    start += neutron_multigroup_data["chi_d_offset"]
    end = start + length
    data[start:end] = value
