# The following is automatically generated by code_factory.py

from numba import njit


@njit
def move_velocities_vector(index_1, source, data, value):
    offset = source["move_velocities_offset"]
    stride = 3
    start = offset + index_1 * stride
    end = start + stride
    data[start:end] = value


@njit
def move_velocities(index_1, index_2, source, data, value):
    offset = source["move_velocities_offset"]
    stride = 3
    data[offset + index_1 * stride + index_2] = value


@njit
def move_velocities_chunk(start, length, source, data, value):
    start += source["move_velocities_offset"]
    end = start + length
    data[start:end] = value


@njit
def move_durations(index, source, data, value):
    offset = source["move_durations_offset"]
    data[offset + index] = value


@njit
def move_durations_all(source, data, value):
    start = source["move_durations_offset"]
    size = source["N_move"]
    end = start + size
    data[start:end] = value


@njit
def move_durations_last(source, data, value):
    start = source["move_durations_offset"]
    size = source["N_move"]
    end = start + size
    data[end - 1] = value


@njit
def move_durations_chunk(start, length, source, data, value):
    start += source["move_durations_offset"]
    end = start + length
    data[start:end] = value


@njit
def move_time_grid(index, source, data, value):
    offset = source["move_time_grid_offset"]
    data[offset + index] = value


@njit
def move_time_grid_all(source, data, value):
    start = source["move_time_grid_offset"]
    size = source["N_move_grid"]
    end = start + size
    data[start:end] = value


@njit
def move_time_grid_last(source, data, value):
    start = source["move_time_grid_offset"]
    size = source["N_move_grid"]
    end = start + size
    data[end - 1] = value


@njit
def move_time_grid_chunk(start, length, source, data, value):
    start += source["move_time_grid_offset"]
    end = start + length
    data[start:end] = value


@njit
def move_translations_vector(index_1, source, data, value):
    offset = source["move_translations_offset"]
    stride = 3
    start = offset + index_1 * stride
    end = start + stride
    data[start:end] = value


@njit
def move_translations(index_1, index_2, source, data, value):
    offset = source["move_translations_offset"]
    stride = 3
    data[offset + index_1 * stride + index_2] = value


@njit
def move_translations_chunk(start, length, source, data, value):
    start += source["move_translations_offset"]
    end = start + length
    data[start:end] = value
