# The following is automatically generated by code_factory.py

from numba import njit


@njit
def scores(index, tally, data, value):
    offset = tally["scores_offset"]
    data[offset + index] = value


@njit
def scores_all(tally, data, value):
    start = tally["scores_offset"]
    size = tally["scores_length"]
    end = start + size
    data[start:end] = value


@njit
def scores_last(tally, data, value):
    start = tally["scores_offset"]
    size = tally["scores_length"]
    end = start + size
    data[end - 1] = value


@njit
def scores_chunk(start, length, tally, data, value):
    start += tally["scores_offset"]
    end = start + length
    data[start:end] = value


@njit
def mu(index, tally, data, value):
    offset = tally["mu_offset"]
    data[offset + index] = value


@njit
def mu_all(tally, data, value):
    start = tally["mu_offset"]
    size = tally["mu_length"]
    end = start + size
    data[start:end] = value


@njit
def mu_last(tally, data, value):
    start = tally["mu_offset"]
    size = tally["mu_length"]
    end = start + size
    data[end - 1] = value


@njit
def mu_chunk(start, length, tally, data, value):
    start += tally["mu_offset"]
    end = start + length
    data[start:end] = value


@njit
def azi(index, tally, data, value):
    offset = tally["azi_offset"]
    data[offset + index] = value


@njit
def azi_all(tally, data, value):
    start = tally["azi_offset"]
    size = tally["azi_length"]
    end = start + size
    data[start:end] = value


@njit
def azi_last(tally, data, value):
    start = tally["azi_offset"]
    size = tally["azi_length"]
    end = start + size
    data[end - 1] = value


@njit
def azi_chunk(start, length, tally, data, value):
    start += tally["azi_offset"]
    end = start + length
    data[start:end] = value


@njit
def energy(index, tally, data, value):
    offset = tally["energy_offset"]
    data[offset + index] = value


@njit
def energy_all(tally, data, value):
    start = tally["energy_offset"]
    size = tally["energy_length"]
    end = start + size
    data[start:end] = value


@njit
def energy_last(tally, data, value):
    start = tally["energy_offset"]
    size = tally["energy_length"]
    end = start + size
    data[end - 1] = value


@njit
def energy_chunk(start, length, tally, data, value):
    start += tally["energy_offset"]
    end = start + length
    data[start:end] = value


@njit
def time(index, tally, data, value):
    offset = tally["time_offset"]
    data[offset + index] = value


@njit
def time_all(tally, data, value):
    start = tally["time_offset"]
    size = tally["time_length"]
    end = start + size
    data[start:end] = value


@njit
def time_last(tally, data, value):
    start = tally["time_offset"]
    size = tally["time_length"]
    end = start + size
    data[end - 1] = value


@njit
def time_chunk(start, length, tally, data, value):
    start += tally["time_offset"]
    end = start + length
    data[start:end] = value


@njit
def bin(index, tally, data, value):
    offset = tally["bin_offset"]
    data[offset + index] = value


@njit
def bin_all(tally, data, value):
    start = tally["bin_offset"]
    size = tally["bin_length"]
    end = start + size
    data[start:end] = value


@njit
def bin_last(tally, data, value):
    start = tally["bin_offset"]
    size = tally["bin_length"]
    end = start + size
    data[end - 1] = value


@njit
def bin_chunk(start, length, tally, data, value):
    start += tally["bin_offset"]
    end = start + length
    data[start:end] = value


@njit
def bin_sum(index, tally, data, value):
    offset = tally["bin_sum_offset"]
    data[offset + index] = value


@njit
def bin_sum_all(tally, data, value):
    start = tally["bin_sum_offset"]
    size = tally["bin_sum_length"]
    end = start + size
    data[start:end] = value


@njit
def bin_sum_last(tally, data, value):
    start = tally["bin_sum_offset"]
    size = tally["bin_sum_length"]
    end = start + size
    data[end - 1] = value


@njit
def bin_sum_chunk(start, length, tally, data, value):
    start += tally["bin_sum_offset"]
    end = start + length
    data[start:end] = value


@njit
def bin_sum_square(index, tally, data, value):
    offset = tally["bin_sum_square_offset"]
    data[offset + index] = value


@njit
def bin_sum_square_all(tally, data, value):
    start = tally["bin_sum_square_offset"]
    size = tally["bin_sum_square_length"]
    end = start + size
    data[start:end] = value


@njit
def bin_sum_square_last(tally, data, value):
    start = tally["bin_sum_square_offset"]
    size = tally["bin_sum_square_length"]
    end = start + size
    data[end - 1] = value


@njit
def bin_sum_square_chunk(start, length, tally, data, value):
    start += tally["bin_sum_square_offset"]
    end = start + length
    data[start:end] = value


@njit
def bin_shape(index, tally, data, value):
    offset = tally["bin_shape_offset"]
    data[offset + index] = value


@njit
def bin_shape_all(tally, data, value):
    start = tally["bin_shape_offset"]
    size = tally["bin_shape_length"]
    end = start + size
    data[start:end] = value


@njit
def bin_shape_last(tally, data, value):
    start = tally["bin_shape_offset"]
    size = tally["bin_shape_length"]
    end = start + size
    data[end - 1] = value


@njit
def bin_shape_chunk(start, length, tally, data, value):
    start += tally["bin_shape_offset"]
    end = start + length
    data[start:end] = value
