# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# assumming this is being done in a repo with trusted publishing permissions in pypi

name: Upload Python Package

on:
    release:
      types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps: 
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - uses: mpi4py/setup-mpi@v1
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install .
        pip install build
    - name: Patch Numba
      run : |
        bash .github/workflows/patch.sh
    - name: Build package
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
        
      #with:
      #  user: __token__
      #  password: ${{ secrets.PYPI_API_TOKEN }}
