name: GPU regression test

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        cd ..
        module load cuda/11.8 gcc/10.3 mpich/4.0h_gcc-10 python/3.11
        module list
        rm -rf ci_testing
        python -m venv ci_testing
        module unload python/3.11
        source ci_testing/bin/activate
        
        pip install --upgrade pip

        cd MCDC
        pip install -e .
        ..

        git clone clone https://github.com/CEMeNT-PSAAP/harmonize.git
        cd harmonize
        pip install -e .
        cd ..

        pip list 
    - name: Regression Test - GPU
      run: |
          cd MCDC/test/regression
          python run.py --mode=numba --target=gpu
