name: Regression Test - MPI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: ["ubuntu-22.04"] #, "macos-latest"
    steps:
    - uses: actions/checkout@v3
    - name: Set up python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: debug
      run: |
        pwd
        ls
    - uses: mpi4py/setup-mpi@v1
    - name: Install dependencies
      run: |
        pip install -e .
        pip list 
    - name: Regression Test - MPI
      run: |
        cd test/regression
        python run.py --mpiexec=4
        python run.py --mpiexec=16 --name=slab_reed_dd_3d
