name: GPU regression test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Load modules and build python venv
      run: |
        pwd
        cd ..
        pwd
        module load cuda/11.8 gcc/10.3 mpich/4.0h_gcc-10 python/3.11
        rm -rf ci_testing
        python -m venv ci_testing
        module unload python/3.11
        source ci_testing/bin/activate
        pip install --upgrade pip
        pwd
    - name: Install MC/DC and Harmonize
      run: |
        source ../ci_testing/bin/activate
        pwd
        pip install -e .
        git clone https://github.com/CEMeNT-PSAAP/harmonize.git
        cd harmonize
        pip install -e .
        cd ..
    - name: Regression Test - GPU
      run: |
          pwd
          source ../ci_testing/bin/activate
          cd test/regression
          python run.py --mode=numba --target=gpu
