name: unit test auto

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: debug
      run: |
        pwd
        ls
    - name: Install dependencies
      run: |
        ./install.sh
    - name: Run Unit Tests
      run: |
        pytest
        cd test/regression
        python run.py
        python run.py --mode=numba
        # TODO: Run regression test with MPI and MPI+Numba
        # TODO: Run performance test
        # TODO: Run GPU test
