name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: debug
      run: |
        pwd
        ls
    - uses: mpi4py/setup-mpi@v1
    - name: Install dependencies
      run: |
        #sudo apt-get install libopenmpi-dev
        pip install numpy numba h5py matplotlib scipy pytest colorama mpi4py
        pip list 
        pip install -e .
    - name: Patch numba
      run : |
        bash .github/workflows/patch.sh
    - name: Run Unit Tests
      run: |
        pytest
        cd test/regression
        python run.py
        python run.py --mpiexec=4 --skip=iqmc*
        python run.py --mode=numba --skip=iqmc*
        python run.py --mpiexec=4 --mode=numba --skip=iqmc*
        # TODO: Run performance test
        # TODO: Run GPU test
