name: Unit Tests

on:
  push:
  pull_request:

jobs:
  unit-test:
    # Temporary suppression while validating Python compatibility on make_release.
    if: github.ref_name != 'make_release' && github.head_ref != 'make_release'
    name: (py${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Show environment info
        run: |
          pwd
          ls
          python --version
          pip --version

      - name: Set up MPI
        uses: mpi4py/setup-mpi@v1

      - name: Install mpi4py
        run: |
          pip install --upgrade pip
          pip install --no-binary=mpi4py mpi4py

      - name: Install MC/DC
        run: |
          pip install -e ".[dev]"
          pip list

      - name: Run unit tests
        run: |
          python -m pytest -v test/unit

      - name: Run public API type checks
        run: pyright
